SAVEPOINT "RESTOREPOINT";
SELECT COUNT(*) FROM (SELECT * FROM  COMPANY WHERE City ='Yangon');
SELECT * FROM  COMPANY WHERE City ='Yangon' LIMIT 0, 49999;
ROLLBACK TO SAVEPOINT "RESTOREPOINT";
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
RELEASE "RESTOREPOINT";
SAVEPOINT "RESTOREPOINT";
SELECT COUNT(*) FROM (SELECT sum (Tax) FROM  COMPANY WHERE  City ='Yangon');
SELECT sum (Tax) FROM  COMPANY WHERE  City ='Yangon' LIMIT 0, 49999;
ROLLBACK TO SAVEPOINT "RESTOREPOINT";
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
RELEASE "RESTOREPOINT";
SAVEPOINT "RESTOREPOINT";
SELECT COUNT(*) FROM (SELECT sum (cogs) FROM  COMPANY WHERE  City ='Yangon' AND 'Mandalay');
SELECT sum (cogs) FROM  COMPANY WHERE  City ='Yangon' AND 'Mandalay' LIMIT 0, 49999;
ROLLBACK TO SAVEPOINT "RESTOREPOINT";
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
RELEASE "RESTOREPOINT";
SAVEPOINT "RESTOREPOINT";
ROLLBACK TO SAVEPOINT "RESTOREPOINT";
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
RELEASE "RESTOREPOINT";
SAVEPOINT "RESTOREPOINT";
ROLLBACK TO SAVEPOINT "RESTOREPOINT";
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
RELEASE "RESTOREPOINT";
SAVEPOINT "RESTOREPOINT";
SELECT COUNT(*) FROM (SELECT sum (cogs) FROM  COMPANY WHERE  City ='Yangon' AND 'Mandalay');
SELECT sum (cogs) FROM  COMPANY WHERE  City ='Yangon' AND 'Mandalay' LIMIT 0, 49999;
ROLLBACK TO SAVEPOINT "RESTOREPOINT";
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
RELEASE "RESTOREPOINT";
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
SELECT COUNT(*) FROM "main"."COMPANY"
SELECT "_rowid_",* FROM "main"."COMPANY" LIMIT 0, 49999;
SAVEPOINT "RESTOREPOINT";
ROLLBACK TO SAVEPOINT "RESTOREPOINT";
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
RELEASE "RESTOREPOINT";
SAVEPOINT "RESTOREPOINT";
SELECT COUNT(*) FROM (SELECT sum(cogs) FROM COMPANY WHERE City in('Yangon''Mandalay'));
SELECT sum(cogs) FROM COMPANY WHERE City in('Yangon''Mandalay') LIMIT 0, 49999;
ROLLBACK TO SAVEPOINT "RESTOREPOINT";
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
RELEASE "RESTOREPOINT";
SAVEPOINT "RESTOREPOINT";
SELECT COUNT(*) FROM (SELECT Sum(cogs) FROM COMPANY WHERE City in('Yangon''Mandalay'));
SELECT Sum(cogs) FROM COMPANY WHERE City in('Yangon''Mandalay') LIMIT 0, 49999;
ROLLBACK TO SAVEPOINT "RESTOREPOINT";
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
RELEASE "RESTOREPOINT";
SAVEPOINT "RESTOREPOINT";
SELECT COUNT(*) FROM (SELECT Sum(cogs) FROM company WHERE City in('Yangon''Mandalay'));
SELECT Sum(cogs) FROM company WHERE City in('Yangon''Mandalay') LIMIT 0, 49999;
ROLLBACK TO SAVEPOINT "RESTOREPOINT";
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
RELEASE "RESTOREPOINT";
SAVEPOINT "RESTOREPOINT";
SELECT COUNT(*) FROM (SELECT Sum(cogs) FROM company WHERE City in('Yangon','Mandalay'));
SELECT Sum(cogs) FROM company WHERE City in('Yangon','Mandalay') LIMIT 0, 49999;
ROLLBACK TO SAVEPOINT "RESTOREPOINT";
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
RELEASE "RESTOREPOINT";
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
SELECT COUNT(*) FROM "main"."COMPANY"
SELECT "_rowid_",* FROM "main"."COMPANY" LIMIT 0, 49999;
SAVEPOINT "RESTOREPOINT";
SELECT COUNT(*) FROM (SELECT Sum(cogs) FROM company WHERE City ='Yangon');
SELECT Sum(cogs) FROM company WHERE City ='Yangon' LIMIT 0, 49999;
ROLLBACK TO SAVEPOINT "RESTOREPOINT";
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
RELEASE "RESTOREPOINT";
SAVEPOINT "RESTOREPOINT";
SELECT COUNT(*) FROM (SELECT Sum(cogs) FROM company WHERE City ='Mandalay');
SELECT Sum(cogs) FROM company WHERE City ='Mandalay' LIMIT 0, 49999;
ROLLBACK TO SAVEPOINT "RESTOREPOINT";
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
RELEASE "RESTOREPOINT";
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
SELECT COUNT(*) FROM "main"."COMPANY"
SELECT "_rowid_",* FROM "main"."COMPANY" LIMIT 0, 49999;
SAVEPOINT "RESTOREPOINT";
SELECT COUNT(*) FROM (SELECT max(gross_margin_percentage) FROM COMPANY);
SELECT max(gross_margin_percentage) FROM COMPANY LIMIT 0, 49999;
ROLLBACK TO SAVEPOINT "RESTOREPOINT";
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
RELEASE "RESTOREPOINT";
SAVEPOINT "RESTOREPOINT";
SELECT COUNT(*) FROM (SELECT max(gross_iincome) FROM COMPANY );
SELECT max(gross_iincome) FROM COMPANY  LIMIT 0, 49999;
ROLLBACK TO SAVEPOINT "RESTOREPOINT";
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
RELEASE "RESTOREPOINT";
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
SELECT "_rowid_",* FROM "main"."COMPANY" LIMIT 0, 49999;
SELECT COUNT(*) FROM "main"."COMPANY"
SAVEPOINT "RESTOREPOINT";
SELECT COUNT(*) FROM (SELECT Customertype, max(InvoiceID) FROM COMPANY );
SELECT Customertype, max(InvoiceID) FROM COMPANY  LIMIT 0, 49999;
ROLLBACK TO SAVEPOINT "RESTOREPOINT";
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
RELEASE "RESTOREPOINT";
SAVEPOINT "RESTOREPOINT";
SELECT COUNT(*) FROM (SELECT Payment,gross_iincome, min(InvoiceID) FROM COMPANY );
SELECT Payment,gross_iincome, min(InvoiceID) FROM COMPANY  LIMIT 0, 49999;
ROLLBACK TO SAVEPOINT "RESTOREPOINT";
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
RELEASE "RESTOREPOINT";
SAVEPOINT "RESTOREPOINT";
SELECT COUNT(*) FROM (SELECT max(cogs),Branch,Gender FROM COMPANY );
SELECT max(cogs),Branch,Gender FROM COMPANY  LIMIT 0, 49999;
ROLLBACK TO SAVEPOINT "RESTOREPOINT";
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
RELEASE "RESTOREPOINT";
SAVEPOINT "RESTOREPOINT";
SELECT COUNT(*) FROM (SELECT max(cogs),Branch,City,gross_iincome,gross_margin_percentage,min(Tax) FROM COMPANY);
SELECT max(cogs),Branch,City,gross_iincome,gross_margin_percentage,min(Tax) FROM COMPANY LIMIT 0, 49999;
ROLLBACK TO SAVEPOINT "RESTOREPOINT";
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
RELEASE "RESTOREPOINT";
